"""add google oauth fields

Revision ID: 3449b99a7a32
Revises: 99c98b3dbe4d
Create Date: 2026-07-07 13:47:36.956224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3449b99a7a32'
down_revision: Union[str, Sequence[str], None] = '99c98b3dbe4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_integrations', sa.Column('access_token', sa.Text(), nullable=True))
    op.add_column('calendar_integrations', sa.Column('refresh_token', sa.Text(), nullable=True))
    op.add_column('calendar_integrations', sa.Column('token_expiry', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('google_sub', sa.String(length=64), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_users_google_sub'), 'users', ['google_sub'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_sub'), table_name='users')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'google_sub')
    op.drop_column('calendar_integrations', 'token_expiry')
    op.drop_column('calendar_integrations', 'refresh_token')
    op.drop_column('calendar_integrations', 'access_token')
    # ### end Alembic commands ###
