"""add confirmed time to meetup_sessions

Revision ID: 6231f9dac445
Revises: a7da4650d7b5
Create Date: 2026-07-13 18:28:30.984712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6231f9dac445'
down_revision: Union[str, Sequence[str], None] = 'a7da4650d7b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetup_sessions', sa.Column('confirmed_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('meetup_sessions', sa.Column('confirmed_end', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetup_sessions', 'confirmed_end')
    op.drop_column('meetup_sessions', 'confirmed_start')
    # ### end Alembic commands ###
