"""add invite_status to session_participants

Revision ID: a7da4650d7b5
Revises: c2ab798c2ae9
Create Date: 2026-07-13 12:45:42.893017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7da4650d7b5'
down_revision: Union[str, Sequence[str], None] = 'c2ab798c2ae9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_participants', sa.Column('invite_status', sa.String(length=20), server_default='pending', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_participants', 'invite_status')
    # ### end Alembic commands ###
