"""add title and status to meetup_sessions

Revision ID: c2ab798c2ae9
Revises: 3449b99a7a32
Create Date: 2026-07-11 23:13:31.287690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2ab798c2ae9'
down_revision: Union[str, Sequence[str], None] = '3449b99a7a32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetup_sessions', sa.Column('title', sa.String(length=100), nullable=False))
    op.add_column('meetup_sessions', sa.Column('status', sa.String(length=20), server_default='matching', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetup_sessions', 'status')
    op.drop_column('meetup_sessions', 'title')
    # ### end Alembic commands ###
