package com.placepick.web;

/** Stable public error identifiers. Internal exception names never cross the HTTP boundary. */
public enum ApiErrorCode {
    INVALID_REQUEST,
    INVALID_CONDITION,
    SESSION_REQUIRED,
    CSRF_INVALID,
    ORIGIN_NOT_ALLOWED,
    RATE_LIMITED,
    PROVIDER_QUOTA_PROTECTED,
    RESOURCE_NOT_FOUND,
    METHOD_NOT_ALLOWED,
    DRAFT_EXPIRED,
    DRAFT_NOT_CONFIRMED,
    DRAFT_ALREADY_CONSUMED,
    JOB_EXPIRED,
    ROOM_EXPIRED,
    ORGANIZER_REQUIRED,
    FINAL_RESULT_CONFLICT,
    RESULT_NOT_FINALIZED,
    IDEMPOTENCY_KEY_REUSED,
    UNPROCESSABLE_CONDITION,
    PROVIDER_RESPONSE_INVALID,
    PROVIDER_UNAVAILABLE,
    INVALID_STATE,
    INTERNAL_ERROR
}
