"""add account_detail to financial_facts

Revision ID: 4206114c5752
Revises: a1023785caf5
Create Date: 2026-07-14 15:11:21.657614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4206114c5752'
down_revision: Union[str, Sequence[str], None] = 'a1023785caf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_facts', sa.Column('account_detail', sa.String(length=255), nullable=True))
    op.drop_constraint(op.f('uq_financial_fact'), 'financial_facts', type_='unique')
    op.create_unique_constraint('uq_financial_fact', 'financial_facts', ['rcept_no', 'fs_div', 'account_id', 'sj_div', 'is_cumulative', 'account_detail'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_financial_fact', 'financial_facts', type_='unique')
    op.create_unique_constraint(op.f('uq_financial_fact'), 'financial_facts', ['rcept_no', 'fs_div', 'account_id', 'sj_div', 'is_cumulative'], postgresql_nulls_not_distinct=False)
    op.drop_column('financial_facts', 'account_detail')
    # ### end Alembic commands ###
