"""add financial_facts table

Revision ID: 4974acb580ff
Revises: 9afeb16760a3
Create Date: 2026-07-14 15:00:02.212686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4974acb580ff'
down_revision: Union[str, Sequence[str], None] = '9afeb16760a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_facts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('corp_code', sa.String(length=8), nullable=False),
    sa.Column('stock_code', sa.String(length=6), nullable=False),
    sa.Column('account_id', sa.String(length=255), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('metric_key', sa.String(length=50), nullable=True),
    sa.Column('raw_value', sa.String(length=30), nullable=False),
    sa.Column('raw_unit', sa.String(length=10), nullable=False),
    sa.Column('normalized_value', sa.Numeric(precision=30, scale=4), nullable=False),
    sa.Column('normalized_unit', sa.String(length=10), nullable=False),
    sa.Column('fiscal_period', sa.String(length=20), nullable=False),
    sa.Column('reprt_code', sa.String(length=5), nullable=False),
    sa.Column('report_type', sa.String(length=10), nullable=False),
    sa.Column('sj_div', sa.String(length=10), nullable=False),
    sa.Column('fs_div', sa.Enum('CFS', 'OFS', name='fs_div'), nullable=False),
    sa.Column('is_cumulative', sa.Boolean(), nullable=False),
    sa.Column('is_provisional', sa.Boolean(), nullable=False),
    sa.Column('is_derived', sa.Boolean(), nullable=False),
    sa.Column('derivation_note', sa.String(length=255), nullable=True),
    sa.Column('rcept_no', sa.String(length=20), nullable=False),
    sa.Column('filed_at', sa.Date(), nullable=False),
    sa.Column('source_url', sa.String(length=255), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rcept_no', 'fs_div', 'account_id', 'sj_div', 'is_cumulative', name='uq_financial_fact')
    )
    op.create_index(op.f('ix_financial_facts_corp_code'), 'financial_facts', ['corp_code'], unique=False)
    op.create_index(op.f('ix_financial_facts_metric_key'), 'financial_facts', ['metric_key'], unique=False)
    op.create_index(op.f('ix_financial_facts_rcept_no'), 'financial_facts', ['rcept_no'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financial_facts_rcept_no'), table_name='financial_facts')
    op.drop_index(op.f('ix_financial_facts_metric_key'), table_name='financial_facts')
    op.drop_index(op.f('ix_financial_facts_corp_code'), table_name='financial_facts')
    op.drop_table('financial_facts')
    # ### end Alembic commands ###
