"""add raw company overview records table

Revision ID: 4abaa8982ee0
Revises: 4206114c5752
Create Date: 2026-07-15 20:07:47.341522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4abaa8982ee0'
down_revision: Union[str, Sequence[str], None] = '4206114c5752'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_company_overview_records',
    sa.Column('raw_record_id', sa.UUID(), nullable=False),
    sa.Column('source_provider', sa.String(length=50), nullable=False),
    sa.Column('corp_code', sa.String(length=8), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('raw_record_id')
    )
    op.create_index(op.f('ix_raw_company_overview_records_corp_code'), 'raw_company_overview_records', ['corp_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_company_overview_records_corp_code'), table_name='raw_company_overview_records')
    op.drop_table('raw_company_overview_records')
    # ### end Alembic commands ###
