"""add market and external evidence tables

Revision ID: 9afeb16760a3
Revises: e8d741dd3a9c
Create Date: 2026-07-14 11:10:18.242167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9afeb16760a3'
down_revision: Union[str, Sequence[str], None] = 'e8d741dd3a9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_external_records',
    sa.Column('raw_record_id', sa.UUID(), nullable=False),
    sa.Column('source_provider', sa.Enum('NAVER_NEWS', 'DATA_GO_KR', 'KRX_OFFICIAL', name='external_source_provider'), nullable=False),
    sa.Column('claim_id', sa.String(length=64), nullable=False),
    sa.Column('query', sa.String(length=500), nullable=False),
    sa.Column('query_builder_version', sa.String(length=50), nullable=False),
    sa.Column('corp_code', sa.String(length=8), nullable=False),
    sa.Column('stock_code', sa.String(length=6), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('raw_record_id')
    )
    op.create_index(op.f('ix_raw_external_records_claim_id'), 'raw_external_records', ['claim_id'], unique=False)
    op.create_index(op.f('ix_raw_external_records_corp_code'), 'raw_external_records', ['corp_code'], unique=False)
    op.create_table('raw_market_records',
    sa.Column('raw_record_id', sa.UUID(), nullable=False),
    sa.Column('source_provider', sa.String(length=50), nullable=False),
    sa.Column('record_type', sa.Enum('CURRENT_PRICE', 'PERIOD_PRICE', 'CORPORATE_ACTION', name='raw_market_record_type'), nullable=False),
    sa.Column('stock_code', sa.String(length=6), nullable=False),
    sa.Column('target_period', sa.String(length=50), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('raw_record_id')
    )
    op.create_index(op.f('ix_raw_market_records_stock_code'), 'raw_market_records', ['stock_code'], unique=False)
    op.create_table('corporate_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stock_code', sa.String(length=6), nullable=False),
    sa.Column('corp_code', sa.String(length=8), nullable=False),
    sa.Column('action_type', sa.Enum('DIVIDEND', 'BONUS_ISSUE', 'PAID_IN_CAPITAL_INCREASE', 'FACE_VALUE_CHANGE', name='corporate_action_type'), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_record_id', sa.UUID(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_record_id'], ['raw_market_records.raw_record_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_code', 'action_type', 'record_date', name='uq_corporate_action')
    )
    op.create_index(op.f('ix_corporate_actions_corp_code'), 'corporate_actions', ['corp_code'], unique=False)
    op.create_index(op.f('ix_corporate_actions_stock_code'), 'corporate_actions', ['stock_code'], unique=False)
    op.create_table('external_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_provider', sa.Enum('NAVER_NEWS', 'DATA_GO_KR', 'KRX_OFFICIAL', name='external_source_provider'), nullable=False),
    sa.Column('corp_code', sa.String(length=8), nullable=False),
    sa.Column('stock_code', sa.String(length=6), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revised_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entity_matched', sa.Boolean(), nullable=False),
    sa.Column('entity_match_text', sa.String(length=255), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('raw_record_id', sa.UUID(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_record_id'], ['raw_external_records.raw_record_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_record_id', 'source_url', name='uq_external_document')
    )
    op.create_index(op.f('ix_external_documents_corp_code'), 'external_documents', ['corp_code'], unique=False)
    op.create_table('quotes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stock_code', sa.String(length=6), nullable=False),
    sa.Column('corp_code', sa.String(length=8), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('price_basis', sa.Enum('ADJUSTED', 'UNADJUSTED', name='price_basis'), nullable=False),
    sa.Column('open_price', sa.String(length=20), nullable=False),
    sa.Column('high_price', sa.String(length=20), nullable=False),
    sa.Column('low_price', sa.String(length=20), nullable=False),
    sa.Column('close_price', sa.String(length=20), nullable=False),
    sa.Column('volume', sa.String(length=20), nullable=False),
    sa.Column('trading_value', sa.String(length=20), nullable=False),
    sa.Column('adjustment_flag_code', sa.String(length=10), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('license', sa.String(length=255), nullable=False),
    sa.Column('raw_record_id', sa.UUID(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_record_id'], ['raw_market_records.raw_record_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_code', 'trade_date', 'price_basis', name='uq_quote')
    )
    op.create_index(op.f('ix_quotes_corp_code'), 'quotes', ['corp_code'], unique=False)
    op.create_index(op.f('ix_quotes_stock_code'), 'quotes', ['stock_code'], unique=False)
    op.create_table('shares_outstanding',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stock_code', sa.String(length=6), nullable=False),
    sa.Column('corp_code', sa.String(length=8), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('shares_outstanding', sa.String(length=20), nullable=False),
    sa.Column('face_value', sa.String(length=20), nullable=False),
    sa.Column('raw_record_id', sa.UUID(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_record_id'], ['raw_market_records.raw_record_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_code', 'as_of_date', name='uq_shares_outstanding')
    )
    op.create_index(op.f('ix_shares_outstanding_corp_code'), 'shares_outstanding', ['corp_code'], unique=False)
    op.create_index(op.f('ix_shares_outstanding_stock_code'), 'shares_outstanding', ['stock_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shares_outstanding_stock_code'), table_name='shares_outstanding')
    op.drop_index(op.f('ix_shares_outstanding_corp_code'), table_name='shares_outstanding')
    op.drop_table('shares_outstanding')
    op.drop_index(op.f('ix_quotes_stock_code'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_corp_code'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_index(op.f('ix_external_documents_corp_code'), table_name='external_documents')
    op.drop_table('external_documents')
    op.drop_index(op.f('ix_corporate_actions_stock_code'), table_name='corporate_actions')
    op.drop_index(op.f('ix_corporate_actions_corp_code'), table_name='corporate_actions')
    op.drop_table('corporate_actions')
    op.drop_index(op.f('ix_raw_market_records_stock_code'), table_name='raw_market_records')
    op.drop_table('raw_market_records')
    op.drop_index(op.f('ix_raw_external_records_corp_code'), table_name='raw_external_records')
    op.drop_index(op.f('ix_raw_external_records_claim_id'), table_name='raw_external_records')
    op.drop_table('raw_external_records')
    # ### end Alembic commands ###
