"""add ord to financial_fact and widen unique constraint

Revision ID: a0bee0a3006f
Revises: a412b659d93a
Create Date: 2026-07-15 20:25:50.731190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0bee0a3006f'
down_revision: Union[str, Sequence[str], None] = 'a412b659d93a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_facts', sa.Column('ord', sa.String(length=10), nullable=True))
    op.drop_constraint(op.f('uq_financial_fact'), 'financial_facts', type_='unique')
    op.create_unique_constraint('uq_financial_fact', 'financial_facts', ['rcept_no', 'fs_div', 'account_id', 'sj_div', 'is_cumulative', 'account_detail', 'ord'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_financial_fact', 'financial_facts', type_='unique')
    op.create_unique_constraint(op.f('uq_financial_fact'), 'financial_facts', ['rcept_no', 'fs_div', 'account_id', 'sj_div', 'is_cumulative', 'account_detail'], postgresql_nulls_not_distinct=False)
    op.drop_column('financial_facts', 'ord')
    # ### end Alembic commands ###
