"""widen financial_fact_row uniqueness to include account_detail

Revision ID: a1023785caf5
Revises: df9bc7f56d7e
Create Date: 2026-07-14 15:06:15.640946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1023785caf5'
down_revision: Union[str, Sequence[str], None] = 'df9bc7f56d7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_financial_fact_row'), 'financial_fact_rows', type_='unique')
    op.create_unique_constraint('uq_financial_fact_row', 'financial_fact_rows', ['rcept_no', 'fs_div', 'account_id', 'sj_div', 'account_detail'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_financial_fact_row', 'financial_fact_rows', type_='unique')
    op.create_unique_constraint(op.f('uq_financial_fact_row'), 'financial_fact_rows', ['rcept_no', 'fs_div', 'account_id', 'sj_div'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
