"""widen financial fact row uniqueness to include ord

Revision ID: a412b659d93a
Revises: 4abaa8982ee0
Create Date: 2026-07-15 20:23:19.452261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a412b659d93a'
down_revision: Union[str, Sequence[str], None] = '4abaa8982ee0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_financial_fact_row'), 'financial_fact_rows', type_='unique')
    op.create_unique_constraint('uq_financial_fact_row', 'financial_fact_rows', ['rcept_no', 'fs_div', 'account_id', 'sj_div', 'account_detail', 'ord'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_financial_fact_row', 'financial_fact_rows', type_='unique')
    op.create_unique_constraint(op.f('uq_financial_fact_row'), 'financial_fact_rows', ['rcept_no', 'fs_div', 'account_id', 'sj_div', 'account_detail'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
