"""add thstrm_add_amount to financial_fact_rows

Revision ID: df9bc7f56d7e
Revises: 4974acb580ff
Create Date: 2026-07-14 15:02:31.790718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df9bc7f56d7e'
down_revision: Union[str, Sequence[str], None] = '4974acb580ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_fact_rows', sa.Column('thstrm_add_amount', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financial_fact_rows', 'thstrm_add_amount')
    # ### end Alembic commands ###
