"""add company and disclosure tables

Revision ID: e8d741dd3a9c
Revises: c4f6e182a5f8
Create Date: 2026-07-13 10:34:37.122740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e8d741dd3a9c'
down_revision: Union[str, Sequence[str], None] = 'c4f6e182a5f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('corp_code', sa.String(length=8), nullable=False),
    sa.Column('corp_name', sa.String(length=255), nullable=False),
    sa.Column('corp_eng_name', sa.String(length=255), nullable=True),
    sa.Column('stock_code', sa.String(length=6), nullable=True),
    sa.Column('listing_status', sa.Enum('LISTED', 'UNLISTED', name='listing_status'), nullable=False),
    sa.Column('source_modify_date', sa.Date(), nullable=False),
    sa.Column('source_batch_id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('corp_code')
    )
    op.create_index(op.f('ix_companies_corp_name'), 'companies', ['corp_name'], unique=False)
    op.create_index(op.f('ix_companies_stock_code'), 'companies', ['stock_code'], unique=False)
    op.create_table('correction_chains',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('corp_code', sa.String(length=8), nullable=False),
    sa.Column('original_rcept_no', sa.String(length=20), nullable=False),
    sa.Column('correction_rcept_no', sa.String(length=20), nullable=False),
    sa.Column('matched_by', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correction_rcept_no', name='uq_correction_rcept_no')
    )
    op.create_index(op.f('ix_correction_chains_corp_code'), 'correction_chains', ['corp_code'], unique=False)
    op.create_table('provider_cache_entries',
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('source_provider', sa.String(length=50), nullable=False),
    sa.Column('response_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('cache_key')
    )
    op.create_table('raw_corp_master_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_provider', sa.String(length=50), nullable=False),
    sa.Column('raw_payload', sa.LargeBinary(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_disclosure_records',
    sa.Column('raw_record_id', sa.UUID(), nullable=False),
    sa.Column('source_provider', sa.String(length=50), nullable=False),
    sa.Column('source_native_id', sa.String(length=50), nullable=True),
    sa.Column('record_type', sa.Enum('DISCLOSURE_LIST_ITEM', 'FINANCIAL_STATEMENT_ROW', 'DOCUMENT_FILE', name='raw_record_type'), nullable=False),
    sa.Column('corp_code', sa.String(length=8), nullable=True),
    sa.Column('stock_code', sa.String(length=6), nullable=True),
    sa.Column('published_at', sa.Date(), nullable=True),
    sa.Column('target_period', sa.String(length=20), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('raw_record_id')
    )
    op.create_index(op.f('ix_raw_disclosure_records_corp_code'), 'raw_disclosure_records', ['corp_code'], unique=False)
    op.create_index(op.f('ix_raw_disclosure_records_source_native_id'), 'raw_disclosure_records', ['source_native_id'], unique=False)
    op.create_table('disclosures',
    sa.Column('rcept_no', sa.String(length=20), nullable=False),
    sa.Column('corp_code', sa.String(length=8), nullable=False),
    sa.Column('report_nm', sa.String(length=255), nullable=False),
    sa.Column('filed_at', sa.Date(), nullable=False),
    sa.Column('flr_nm', sa.String(length=255), nullable=True),
    sa.Column('corp_cls', sa.String(length=1), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('report_type', sa.Enum('ANNUAL', 'Q1', 'HALF', 'Q3', 'OTHER', name='report_type'), nullable=False),
    sa.Column('is_correction', sa.Boolean(), nullable=False),
    sa.Column('raw_record_id', sa.UUID(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_record_id'], ['raw_disclosure_records.raw_record_id'], ),
    sa.PrimaryKeyConstraint('rcept_no')
    )
    op.create_index(op.f('ix_disclosures_corp_code'), 'disclosures', ['corp_code'], unique=False)
    op.create_table('document_chunks',
    sa.Column('presentation_item_id', sa.UUID(), nullable=False),
    sa.Column('rcept_no', sa.String(length=20), nullable=False),
    sa.Column('corp_code', sa.String(length=8), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('chunk_offset', sa.Integer(), nullable=False),
    sa.Column('target_period', sa.String(length=20), nullable=True),
    sa.Column('filed_at', sa.Date(), nullable=False),
    sa.Column('integrity_status', sa.String(length=20), nullable=False),
    sa.Column('raw_record_id', sa.UUID(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_record_id'], ['raw_disclosure_records.raw_record_id'], ),
    sa.PrimaryKeyConstraint('presentation_item_id'),
    sa.UniqueConstraint('rcept_no', 'chunk_index', name='uq_document_chunk')
    )
    op.create_index(op.f('ix_document_chunks_corp_code'), 'document_chunks', ['corp_code'], unique=False)
    op.create_index(op.f('ix_document_chunks_rcept_no'), 'document_chunks', ['rcept_no'], unique=False)
    op.create_table('financial_fact_rows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rcept_no', sa.String(length=20), nullable=False),
    sa.Column('corp_code', sa.String(length=8), nullable=False),
    sa.Column('bsns_year', sa.String(length=4), nullable=False),
    sa.Column('reprt_code', sa.String(length=5), nullable=False),
    sa.Column('fs_div', sa.String(length=3), nullable=False),
    sa.Column('sj_div', sa.String(length=10), nullable=False),
    sa.Column('sj_nm', sa.String(length=50), nullable=False),
    sa.Column('account_id', sa.String(length=255), nullable=False),
    sa.Column('account_nm', sa.String(length=255), nullable=False),
    sa.Column('account_detail', sa.String(length=255), nullable=True),
    sa.Column('thstrm_nm', sa.String(length=50), nullable=True),
    sa.Column('thstrm_amount', sa.String(length=50), nullable=True),
    sa.Column('frmtrm_nm', sa.String(length=50), nullable=True),
    sa.Column('frmtrm_amount', sa.String(length=50), nullable=True),
    sa.Column('bfefrmtrm_nm', sa.String(length=50), nullable=True),
    sa.Column('bfefrmtrm_amount', sa.String(length=50), nullable=True),
    sa.Column('ord', sa.String(length=10), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('filed_at', sa.Date(), nullable=False),
    sa.Column('is_eligible', sa.Boolean(), nullable=False),
    sa.Column('raw_record_id', sa.UUID(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_record_id'], ['raw_disclosure_records.raw_record_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rcept_no', 'fs_div', 'account_id', 'sj_div', name='uq_financial_fact_row')
    )
    op.create_index(op.f('ix_financial_fact_rows_corp_code'), 'financial_fact_rows', ['corp_code'], unique=False)
    op.create_index(op.f('ix_financial_fact_rows_rcept_no'), 'financial_fact_rows', ['rcept_no'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financial_fact_rows_rcept_no'), table_name='financial_fact_rows')
    op.drop_index(op.f('ix_financial_fact_rows_corp_code'), table_name='financial_fact_rows')
    op.drop_table('financial_fact_rows')
    op.drop_index(op.f('ix_document_chunks_rcept_no'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_corp_code'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_disclosures_corp_code'), table_name='disclosures')
    op.drop_table('disclosures')
    op.drop_index(op.f('ix_raw_disclosure_records_source_native_id'), table_name='raw_disclosure_records')
    op.drop_index(op.f('ix_raw_disclosure_records_corp_code'), table_name='raw_disclosure_records')
    op.drop_table('raw_disclosure_records')
    op.drop_table('raw_corp_master_batches')
    op.drop_table('provider_cache_entries')
    op.drop_index(op.f('ix_correction_chains_corp_code'), table_name='correction_chains')
    op.drop_table('correction_chains')
    op.drop_index(op.f('ix_companies_stock_code'), table_name='companies')
    op.drop_index(op.f('ix_companies_corp_name'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
