"""nulls not distinct for financial fact row and financial fact uniqueness

Revision ID: ff931b51a413
Revises: a0bee0a3006f
Create Date: 2026-07-15 22:17:26.635246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff931b51a413'
down_revision: Union[str, Sequence[str], None] = 'a0bee0a3006f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_financial_fact_row'), 'financial_fact_rows', type_='unique')
    op.create_unique_constraint('uq_financial_fact_row', 'financial_fact_rows', ['rcept_no', 'fs_div', 'account_id', 'sj_div', 'account_detail', 'ord'], postgresql_nulls_not_distinct=True)
    op.drop_constraint(op.f('uq_financial_fact'), 'financial_facts', type_='unique')
    op.create_unique_constraint('uq_financial_fact', 'financial_facts', ['rcept_no', 'fs_div', 'account_id', 'sj_div', 'is_cumulative', 'account_detail', 'ord'], postgresql_nulls_not_distinct=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_financial_fact', 'financial_facts', type_='unique')
    op.create_unique_constraint(op.f('uq_financial_fact'), 'financial_facts', ['rcept_no', 'fs_div', 'account_id', 'sj_div', 'is_cumulative', 'account_detail', 'ord'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_financial_fact_row', 'financial_fact_rows', type_='unique')
    op.create_unique_constraint(op.f('uq_financial_fact_row'), 'financial_fact_rows', ['rcept_no', 'fs_div', 'account_id', 'sj_div', 'account_detail', 'ord'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
